<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h4 mb-0">Contactos</h1><a href="<?= e(url('/app/clientes')) ?>" class="btn btn-outline-primary btn-sm">Volver a clientes</a></div>
<div class="card mb-3"><div class="card-header">Nuevo contacto</div><div class="card-body"><form method="POST" action="<?= e(url('/app/contactos')) ?>" class="row g-2"><?= csrf_campo() ?>
<div class="col-md-3"><label class="form-label">Cliente</label><select name="cliente_id" class="form-select" required><?php foreach($clientes as $c): ?><option value="<?= (int)$c['id'] ?>"><?= e($c['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label">Nombre</label><input name="nombre" class="form-control" required></div>
<div class="col-md-2"><label class="form-label">Cargo</label><input name="cargo" class="form-control"></div>
<div class="col-md-2"><label class="form-label">Correo</label><input type="email" name="correo" class="form-control"></div>
<div class="col-md-2"><label class="form-label">Teléfono</label><input name="telefono" class="form-control"></div>
<div class="col-md-2"><label class="form-label">Celular</label><input name="celular" class="form-control"></div>
<div class="col-md-2"><label class="form-label">Principal</label><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="es_principal" value="1"><label class="form-check-label">Sí</label></div></div>
<div class="col-md-8"><label class="form-label">Observaciones</label><input name="observaciones" class="form-control"></div>
<div class="col-12"><button class="btn btn-primary btn-sm">Guardar contacto</button></div>
</form></div></div>
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><div class="d-flex gap-2 align-items-center"><label class="small">Mostrar</label><select class="form-select form-select-sm" style="width:90px"><option>10</option><option>25</option></select></div><form class="d-flex gap-2"><input class="form-control form-control-sm" name="q" value="<?= e($buscar) ?>" placeholder="Buscar contacto"><button class="btn btn-outline-secondary btn-sm">Buscar</button></form></div><div class="table-responsive" style="overflow: visible;"><table class="table table-sm table-hover mb-0 tabla-admin"><thead><tr><th>Cliente ID</th><th>Nombre</th><th>Cargo</th><th>Correo</th><th>Teléfono</th><th>Principal</th><th class="text-end">Acciones</th></tr></thead><tbody><?php foreach($contactos as $r): ?><tr><td>#<?= (int)$r['cliente_id'] ?></td><td><?= e($r['nombre']) ?></td><td><?= e($r['cargo']) ?></td><td><?= e($r['correo']) ?></td><td><?= e($r['telefono']) ?></td><td><?= !empty($r['es_principal']) ? 'Sí' : 'No' ?></td><td class="text-end"><div class="dropdown dropup"><button class="btn btn-light btn-sm dropdown-toggle" data-bs-toggle="dropdown">Acciones</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?= e(url('/app/contactos/ver/' . $r['id'])) ?>">Ver</a></li><li><a class="dropdown-item" href="<?= e(url('/app/contactos/editar/' . $r['id'])) ?>">Editar</a></li><li><form method="POST" action="<?= e(url('/app/contactos/eliminar/' . $r['id'])) ?>" onsubmit="return confirm('¿Eliminar contacto?')"><?= csrf_campo() ?><button type="submit" class="dropdown-item text-danger">Eliminar</button></form></li></ul></div></td></tr><?php endforeach; ?></tbody></table></div></div>
